import
"D:\\dlmsdk\\DLP\\Examples\\aeobject\\mac\\aeobject.d32";


str=aeTStringList;

str.LoadFromFile("D:\\dlmsdk\\DLP\\Examples\\aeobject\\mac\\111.txt");
str.Add("6666666666");
str.SaveToFile("D:\\dlmsdk\\DLP\\Examples\\aeobject\\mac\\111.txt");
println(str.Count);
println(str.Strings(0));
println(str.Strings(1));
println(str.Strings(2));
println(str.Strings(3));
println(str.Strings(4));
str.Clear();
/*println(str.Strings(5));*/
/*println(str.item)*/
